name: Build and Publish Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: maven

      - name: Build the application
        run: mvn clean package

      - name: Get current version
        id: get_version
        run: |
          DATE=$(date +'%Y.%m.%d')
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          VERSION="$DATE-$SHORT_COMMIT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
